# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.BooleanField(default=False),
        ),
    ]
