# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0002_auto_20180222_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img/default-avatar.jpg', upload_to=''),
        ),
    ]
