# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0003_auto_20180222_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Title')),
                ('category', models.CharField(default='', max_length=200, null=True, verbose_name='Category')),
                ('url', models.URLField(default='', verbose_name='Url')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Short description')),
                ('price', models.CharField(default='', max_length=200, null=True, verbose_name='Price')),
                ('sale_price', models.CharField(default='', max_length=200, null=True, verbose_name='Sale price')),
                ('currency', models.CharField(default='', max_length=200, null=True, verbose_name='Currency')),
                ('images', models.CharField(default='', max_length=2000, verbose_name='Image URLs')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2018, 2, 22, 9, 34, 10, 242137), verbose_name='Time Extracted')),
                ('options', models.CharField(default='', max_length=2000, verbose_name='Options')),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ShopifySettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('proxy_api', models.CharField(default='', max_length=100, verbose_name='Proxy api key')),
                ('update_period', models.IntegerField(default=60, verbose_name='Update after (sec)')),
            ],
            options={
                'verbose_name': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='ShopifySiteCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ShopifySiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(default='http://example.com', max_length=100, verbose_name='Url')),
                ('total_products', models.IntegerField(default=0, verbose_name='Total products')),
                ('last_update_date', models.DateTimeField(default=datetime.datetime(2018, 2, 22, 9, 34, 10, 241057), verbose_name='Date Updated')),
                ('site_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopsify_admin.ShopifySiteCategoryModel', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.AddField(
            model_name='shopifyproductmodel',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopsify_admin.ShopifySiteModel', verbose_name='Parent website'),
        ),
    ]
