# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0008_auto_20180222_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysitemodel',
            name='site_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopsify_admin.ShopifySiteCategoryModel', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 10, 31, 35, 698608), verbose_name='Time Extracted'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 10, 31, 35, 697183), verbose_name='Date Updated'),
        ),
    ]
