# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0009_auto_20180222_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysitemodel',
            name='status',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 11, 58, 41, 594793), verbose_name='Time Extracted'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 11, 58, 41, 593658), verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default-avatar.jpg', upload_to=''),
        ),
    ]
