# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0010_auto_20180224_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproductmodel',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 25, 9, 19, 51, 100796), verbose_name='Time Extracted'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 25, 9, 19, 51, 99600), verbose_name='Date Updated'),
        ),
    ]
