# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0011_auto_20180225_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 3, 33, 39, 925279), verbose_name='Time Extracted'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 3, 33, 39, 924138), verbose_name='Date Updated'),
        ),
    ]
