# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0012_auto_20180227_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 9, 5, 51, 373098), verbose_name='Time Extracted'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 9, 5, 51, 371964), verbose_name='Date Updated'),
        ),
    ]
