# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsify_admin', '0013_auto_20180302_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 9, 6, 2, 57445), verbose_name='Time Extracted'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 9, 6, 2, 55481), verbose_name='Date Updated'),
        ),
    ]
